### ISSUE TITLE
数值不足千时 ,  使用千分位 结果前面 多了个 ,

### ISSUE THREAD

**Issue by OriginalCobra** [13601313270/vue-format#2]
难道要判断下是否>=1000 吗 ?

我是在绑定列表时使用的

**Comment by thk-liu** [comment]
我也遇到同样的问题了，还是改回accountjs做显示兼容性太差

**Comment by OriginalCobra** [comment]
我是v-format时判断了下是否 >=1000

**Comment by 13601313270** [comment]
不好意思，大家久等，1.2.6已经解决。 @OriginalCobra @thk-liu
