### ISSUE TITLE
小数点都是0的无法千分位表示

### ISSUE THREAD

**Issue by xckouy** [13601313270/vue-format#3]
<div v-format="'#,##0.00'">19526.00</div>
结果：19526.00
期望：19,526.00或19,526

**Comment by 13601313270** [comment]
针对19526.00这个数字

配置的格式，可以配制成

#,###.00     生成的就是  19,526.00
#,###          生成的就是  19,526


========================格式介绍=======================

【 # 】数字占位符
只显有意义的零而不显示无意义的零。小数点后数字如大于”#”的数量，则按”#”的位数四舍五入。

【 0 】数字占位符
如果单元格的内容大于占位符，则显示实际数字，如果小于点位符的数量，则用0补足。


更多的格式信息，可以阅读ReadMe里面的内容

**Comment by 13601313270** [comment]
针对19526.00这个数字

配置的格式，可以配制成

#,###.00 生成的就是 19,526.00
#,### 生成的就是 19,526

========================格式介绍=======================

【 # 】数字占位符
只显有意义的零而不显示无意义的零。小数点后数字如大于”#”的数量，则按”#”的位数四舍五入。

【 0 】数字占位符
如果单元格的内容大于占位符，则显示实际数字，如果小于点位符的数量，则用0补足。

更多的格式信息，可以阅读ReadMe里面的内容
